# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export ZDOTDIR="$HOME/.dotfiles/zsh"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


## Source .bashrc if present
if [[ -s "$HOME/.bashrc" ]]; then
  source "$HOME/.bashrc"
fi


if [[ -s "/usr/local/go/" ]] || [[ -s "/usr/local/bin/go/" ]]; then
  export GOPATH=$HOME/.go
  export PATH=$PATH:$GOPATH/bin
fi
