#
# Defines environment variables.
#
# CB –
# This file must be symlinked to home directory in order to pull Dropbox Prezto configuration
# $ ln -s ~/Dropbox/Computer\ Preferences/zsh/.zprezto/runcoms/zshenv ~/.zshenv

# Restore old bash preferences
if [ -f ~/.bash_profile ]; then
  . ~/.bash_profile
fi

# If on a VM (eg. Vagrant box), refer to host machine's zsh preferences
export ZDOTDIR="${HOSTHOME:-$HOME}/Dropbox/Computer Preferences/zsh"


if [[ "$SHLVL" -eq 1 && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
  PATH=$HOME/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/terraform/bin:$HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:$PATH
fi
