#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# it2prof allows for changing color schemes of iTerm2
# Eg. `it2prof <profile name>`
it2prof() { echo -e "\033]50;SetProfile=$1\a"  }

# Customize to your needs...
alias 'll=ls -lah'

## Source rbenv if present
if hash rbenv 2>/dev/null; then
  eval "$(rbenv init -)"
fi

## `chpwd` always executes whenever the current working directory is changed
## List directory contents whenever the current working directory is changed
function chpwd() {
  ll
}
