#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias 'll=ls -lah'

## Source rbenv if present
if hash rbenv 2>/dev/null; then
  eval "$(rbenv init -)"
fi

## `chpwd` always executes whenever the current working directory is changed
## List directory contents whenever the current working directory is changed
function chpwd() {
  ll
}

## INCOMPLETE
## Source .bashrc if present
if [[ -s "$HOME/.bashrc" ]]; then
  source "$HOME/.bashrc"
fi
